applications:
  - name: example-app   # application name in Argo CD
    namespace: default  # Kubernetes namespace
    project: default    # Argo CD project name
    source:             # application source code
      # repoURL: https://github.com/YOUR_USERNAME/example-repo.git
      repoURL: ${github_repo_url} # link to the Git repository where Helm charts or Kubernetes manifests are stored
      path: charts/node-app       # path inside the repository to the required chart or YAML files
      targetRevision: lesson-9    # branch or Git tag to pull the app from (e.g., main)
      helm:
        valueFiles:               # list of values files to pass to the Helm chart
          - values.yaml
    destination:                              # specifies where to deploy the application
      server: https://kubernetes.default.svc  # Kubernetes API server address; for in-cluster use https://kubernetes.default.svc
      namespace: default                      # Kubernetes namespace for this particular application
    syncPolicy:           # synchronization policy
      automated:          # enables automatic application of changes
        prune: true       # delete resources no longer described in Git
        selfHeal: true    # automatically correct drift from Git state if something changed manually in the cluster

repositories:
  - name: example-app         # repository name for internal use
    # url: https://github.com/YOUR_USERNAME/example-repo.git
    url: ${github_repo_url}   # full URL of the Git repository
    username: ${github_user}  # credentials for accessing the private repository
    password: ${github_pat}

repoConfig:
  insecure: "true"    # allow connecting to the repository without SSL certificate verification; not recommended for production
  enableLfs: "true"   # enable Git LFS (Large File Storage) if large files are stored in the repository
